### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by nestyxx** [jampe/kp2bw#16]
**Describe the bug**
'utf-8' codec can't decode byte 0x82 in position 80: invalid start byte

INFO: Found xx entries in KeePass DB. Parsing now...
INFO: Parsed xx entries
Traceback (most recent call last):
  File "\kp2bw-master\kp2bw\kp2bw.py", line 76, in <module>
    c.convert()
  File "\kp2bw-master\kp2bw\convert.py", line 225, in convert
    self._create_bitwarden_items_for_entries()
  File "\kp2bw-master\kp2bw\convert.py", line 186, in _create_bitwarden_items_for_entries
    bw = BitwardenClient(self._bitwarden_password)
  File "s\kp2bw-master\kp2bw\bitwardenclient.py", line 14, in __init__
    if not "bitwarden" in self._exec("bw"):
  File "\kp2bw-master\kp2bw\bitwardenclient.py", line 40, in _exec
    return str(output.decode("utf-8"))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 80: invalid start byte

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1 19041.1165
 - Python version: Python 3.9.6 / pip 21.2.4
 - Bitwarden cli version: 1.17.1

**Comment by nestyxx** [comment]
Line 40
# return str(output.decode("utf-8"))
return str(output.decode("utf-8","ignore"))

Test OK with # caracters in KeePass.
