### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by Ciantic** [jampe/kp2bw#2]
I was attempting to import some items, and I got this:

```
Traceback (most recent call last):
  File "kp2bw/kp2bw/kp2bw.py", line 63, in <module>
    c.convert()
  File "C:\BitwardenTests\kp2bw\kp2bw\convert.py", line 219, in convert
    self._create_bitwarden_items_for_entries()
  File "C:\BitwardenTests\kp2bw\kp2bw\convert.py", line 195, in _create_bitwarden_items_for_entries
    output = bw.create_entry(folder, bw_item_object)
  File "C:\BitwardenTests\kp2bw\kp2bw\Bitwardenclient.py", line 47, in create_entry
    self.create_folder(folder)
  File "C:\BitwardenTests\kp2bw\kp2bw\Bitwardenclient.py", line 42, in create_folder
    output_obj = json.loads(output)
  File "c:\copies\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "c:\copies\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\copies\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Not sure what is the problem yet.

**Comment by Ciantic** [comment]
interesting, it's now working as I retrieved the latest commit you made. some weird errors still.

**Comment by Ciantic** [comment]
Oh it's not working, it gives me bunch of successes but it didn't work.

```
[1 of 160] Creating Bitwarden entry in None for site1...
[2 of 160] Creating Bitwarden entry in None for site2...
[3 of 160] Creating Bitwarden entry in None for site3...
[4 of 160] Creating Bitwarden entry in None for site4...
[5 of 160] Creating Bitwarden entry in None for site5...
```

JSONDecodeError disappeared, but now I get these inside BW: 
```
!! ERROR: Creation of entry failed: (node:14904) UnhandledPromiseRejectionWarning: Error: Unknown cipher type.
    at cipher_service_CipherService.<anonymous> (C:\Copies\Node\node_modules\@bitwarden\cli\build\bw.js:4236:27)
    at Generator.next (<anonymous>)
    at C:\Copies\Node\node_modules\@bitwarden\cli\build\bw.js:3371:71
    at new Promise (<anonymous>)
    at cipher_service_awaiter (C:\Copies\Node\node_modules\@bitwarden\cli\build\bw.js:3367:12)
    at cipher_service_CipherService.encryptCipherData (C:\Copies\Node\node_modules\@bitwarden\cli\build\bw.js:4175:16)
    at cipher_service_CipherService.<anonymous> (C:\Copies\Node\node_modules\@bitwarden\cli\build\bw.js:3497:22)
    at Generator.next (<anonymous>)
    at C:\Copies\Node\node_modules\@bitwarden\cli\build\bw.js:3371:71
    at new Promise (<anonymous>)
(node:14904) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:14904) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jampe** [comment]
first of all, thanks for testing :)

this looks like an error by the bitwarden cli tool to me. Which os do you use? And do you use bitwarden.com or an on premise installation? Cipher problem could be something with the TLS connection to the server, could there be a problem with the certificate?

I just pushed the support for verbose output (-v flag) which outputs the executed bw commands and the responses if set. Can you use this to check if your bw cli installation is the problem? i would recommend to execute some commands manually in a shell and check the output.

**Comment by Ciantic** [comment]
I'm using Windows 10, I will try again inside Linux Docker container when I have time to create proper `Dockerfile` for this. It's probably a problem with crappy Windows command prompt, boy I don't like that.

I ran with `-v` switch but can't yet make head or tails from the output.

Btw, `bw list items` works correctly so it somehow works.

**Comment by jampe** [comment]
Quick status update: I just checked it out in a Windows VM. Looks like a Windows / PowerShell related quote escaping bug. I'll trace it further and push the fix later.
