### ISSUE TITLE
Attachments fail to create temporary dir

### ISSUE THREAD

**Issue by v4rakh** [jampe/kp2bw#25]
**Describe the bug**
Attachments don't work, but entry is created with no attachments, some weird imports happening with `os.os`

**Provide verbose program output**

Removed the actual JSON output provided by `-v` as it contains private data. Still the cause should be clear, it's _after_ the item has been created successfully.

```
DEBUG:   |- Output: b'{"object":"item","id":"14b037d9-5bf2-489d-9ebe-484cf7308c3f","organizationId":null,"folderId":"f34b9e66-93bc-4535-9cef-f545d92634b3","type":1,"reprompt":0,"name":"MYITEM","notes":"See attached file","favorite":false,"login":{"uris":[],"username":null,"password":".....","totp":null,"passwordRevisionDate":null},"collectionIds":[],"revisionDate":"2022-03-01T22:07:31.694Z"}'

...

INFO:         - Uploading attachment for item MY_ENTRY...
Traceback (most recent call last):
  File "/home/varakh/.local/bin/kp2bw", line 8, in <module>
    sys.exit(main())
  File "/home/varakh/.local/lib/python3.10/site-packages/kp2bw/cli.py", line 69, in main
    c.convert()
  File "/home/varakh/.local/lib/python3.10/site-packages/kp2bw/convert.py", line 225, in convert
    self._create_bitwarden_items_for_entries()
  File "/home/varakh/.local/lib/python3.10/site-packages/kp2bw/convert.py", line 210, in _create_bitwarden_items_for_entries
    res = bw.create_attachement(item_id, attachment)
  File "/home/varakh/.local/lib/python3.10/site-packages/kp2bw/bitwardenclient.py", line 131, in create_attachement
    self._create_temporary_attachment_folder()
  File "/home/varakh/.local/lib/python3.10/site-packages/kp2bw/bitwardenclient.py", line 40, in _create_temporary_attachment_folder
    os.os.mkdir(self.TEMPORARY_ATTACHMENT_FOLDER)
AttributeError: module 'os' has no attribute 'os'
```

The `os.os` looks wrong to me.

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Python version: Python 3.10.2
 - Bitwarden cli version: 1.21.1
 - Installed via whl, but get the same error when installing with venv
 - Have `python-pip` and `python-wheel` installed but same error when pip installs via legacy setup install when wheel package is unavailable

**Additional context**

Output of `pip show kp2bw`

```bash
Name: kp2bw
Version: 1.1
Summary: Imports and existing KeePass db with REF fields into Bitwarden,
Home-page: https://github.zhaw.ch/jampe/kp2bw
Author: Daniel Jampen
Author-email: daniel@jampen.net
License: UNKNOWN
Location: /home/varakh/.local/lib/python3.10/site-packages
Requires: pykeepass
Required-by:
```

**Other proposal**
* If consistent creation of an item fails, I would propose to rather delete the inconsistent item, otherwise it will be skipped next time, maybe it succeeds there, but users will be left with an inconsistent state then.
* Add a flag to skip attachments entirely? Then import will work and one could manually handle attachments

**Comment by v4rakh** [comment]
I've just retried from sources and it works now. I think the whl needs to be updated though.
