### ISSUE TITLE
More of a BW issue, but seen here

### ISSUE THREAD

**Issue by terribletrouble** [jampe/kp2bw#38]
I just logged this on BW community site:

From what I can see, purely a bw issue, but this has meant I cannot convert any of my Keepass over to Vaultwarden. 
You guys may have seen this, or know a work around....?

Running bw --version 2023.1.0
Running on Ubuntu 22.04 - bw installed via snap.
Attempting to add an attachment to an existing record:

bw create attachment --file ./hist.txt --itemid REDACTED --session ‘REDACTED’
node:fs:585
handleErrorFromBinding(ctx);
^

Error: EACCES: permission denied, open ‘/home/jason/hist.txt’
at Object.openSync (node:fs:585:3)
at Object.openSync (pkg/prelude/bootstrap.js:796:32)
at Object.readFileSync (node:fs:453:35)
at Object.readFileSync (pkg/prelude/bootstrap.js:1082:36)
at CreateCommand. (/snapshot/clients/apps/cli/build/bw.js:31997:55)
at Generator.next ()
at /snapshot/clients/apps/cli/build/bw.js:31900:71
at new Promise ()
at /snapshot/clients/apps/cli/build/bw.js:31896:12
at CreateCommand.createAttachment (/snapshot/clients/apps/cli/build/bw.js:31979:16) {
errno: -13,
syscall: ‘open’,
code: ‘EACCES’,
path: ‘/home/jason/hist.txt’
}

ls -asl hist.txt 
8 -rw-rw-r-- 1 jason jason 7466 Jan 21 23:15 hist.txt

**Comment by jampe** [comment]
closing as its a problem with bw not kp2bw. Please check with the guys maintaining the bw snap package
